<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/hastaKabulDatabaseReference"
                xmlns:ns0="http://xmlns.oracle.com/HastaneYonetimBilgiSistemi/HastaKabul/HastaKabulBpel"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/HastaneYonetimBilgiSistemi/HastaKabul/hastaKabulDatabaseReference"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/HastaKabulBpel.wsdl"/>
                <oracle-xsl-mapper:rootElement name="hastaKabul"
                                               namespace="http://xmlns.oracle.com/HastaneYonetimBilgiSistemi/HastaKabul/HastaKabulBpel"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/hastaKabulDatabaseReference.wsdl"/>
                <oracle-xsl-mapper:rootElement name="HastaKabulCollection"
                                               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/hastaKabulDatabaseReference"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE OCT 21 11:54:46 EEST 2014].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:HastaKabulCollection>
            <tns:HastaKabul>
                <tns:hastaTckimlikNo>
                    <xsl:value-of select="/ns0:hastaKabul/ns0:hastaTCKimlikNo"/>
                </tns:hastaTckimlikNo>
                <tns:provizyonTarihi>
                    <xsl:value-of select="/ns0:hastaKabul/ns0:provizyonTarihi"/>
                </tns:provizyonTarihi>
                <tns:saglikTesisKodu>
                    <xsl:value-of select="/ns0:hastaKabul/ns0:saglikTesisKodu"/>
                </tns:saglikTesisKodu>
                <tns:bransKodu>
                    <xsl:value-of select="/ns0:hastaKabul/ns0:bransKodu"/>
                </tns:bransKodu>
                <tns:tedaviTuru>
                    <xsl:value-of select="/ns0:hastaKabul/ns0:tedaviTuru"/>
                </tns:tedaviTuru>
                <tns:takipTipi>
                    <xsl:value-of select="/ns0:hastaKabul/ns0:takipTipi"/>
                </tns:takipTipi>
            </tns:HastaKabul>
        </tns:HastaKabulCollection>
    </xsl:template>
</xsl:stylesheet>
