<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.oracle.com/ThrowCatchExampleApp/ThrowCatchExampleProject/ThrowCatchBpelProcess"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ThrowCatchBpelProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="processFault"
                                       namespace="http://xmlns.oracle.com/ThrowCatchExampleApp/ThrowCatchExampleProject/ThrowCatchBpelProcess"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ThrowCatchBpelProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="processResponse"
                                       namespace="http://xmlns.oracle.com/ThrowCatchExampleApp/ThrowCatchExampleProject/ThrowCatchBpelProcess"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE OCT 21 16:47:46 EEST 2014].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:processResponse>
      <xsl:choose>
        <xsl:when test="string-length(normalize-space(/ns0:processFault/ns0:errorCode)) != 0 and string-length(normalize-space(/ns0:processFault/ns0:errorMessage)) != 0">
          <ns0:resultCode>
            <xsl:value-of select="/ns0:processFault/ns0:errorCode"/>
          </ns0:resultCode>
          <ns0:resultMessage>
            <xsl:value-of select="/ns0:processFault/ns0:errorMessage"/>
          </ns0:resultMessage>
        </xsl:when>
        <xsl:otherwise>
          <ns0:resultCode>
            <xsl:value-of select="'11'"/>
          </ns0:resultCode>
          <ns0:resultMessage>
            <xsl:value-of select="'Unexpected error'"/>
          </ns0:resultMessage>
        </xsl:otherwise>
      </xsl:choose>
    </ns0:processResponse>
  </xsl:template>
</xsl:stylesheet>
