<wsdl:definitions
     name="dbReferencedForCount"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SubprocessApp/StandaloneSubProcessProject/dbReferencedForCount"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SubprocessApp/StandaloneSubProcessProject/dbReferencedForCount"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbReferencedForCount"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReferencedForCount_plt" >
    <plt:role name="dbReferencedForCount_role" >
      <plt:portType name="tns:dbReferencedForCount_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="dbReferencedForCount_plt" >
    <plt:role name="dbReferencedForCount_role" >
      <plt:portType name="tns:dbReferencedForCount_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbReferencedForCount" schemaLocation="../Schemas/dbReferencedForCount.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbReferencedForCount" schemaLocation="../Schemas/dbReferencedForCount.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbReferencedForCountInput_msg">
        <wsdl:part name="dbReferencedForCountInput_msg" element="db:dbReferencedForCountInput"/>
    </wsdl:message>
    <wsdl:message name="dbReferencedForCountOutput_msg">
        <wsdl:part name="dbReferencedForCountOutput" element="db:dbReferencedForCountOutput"/>
    </wsdl:message>
    <wsdl:portType name="dbReferencedForCount_ptt">
        <wsdl:operation name="dbReferencedForCount">
            <wsdl:input message="tns:dbReferencedForCountInput_msg"/>
            <wsdl:output message="tns:dbReferencedForCountOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
